### ISSUE TITLE
Is it possible to add missing Serbian alphabet?

### ISSUE THREAD

**Issue by Aracki** [xfslove/alfred-language-configuration#1]
The Serbian language uses two alphabets and if I want to translate from `SR(Cyrillic)->EN` I don't have issues.

But in the case of `SR(Latin)->EN`, Google Translate will automatically change my input from Latin to Cyrillic and then do the translation, **_which is not the case with this Alfred workflow_**.

I've found this [support google thread](https://support.google.com/translate/thread/1836538?msgid=4351731) where it says they have `sr-Latn` as language code. Can we add it to the list of languages?

**Comment by xfslove** [comment]
Hi, @Aracki sorry for lated reply, I'm just watching the main repository(alfred-google-translate) and not watching this. 

I'm not good at the Serbian language, so cannot check if the `sr-Latn` works(because of the api limitation, we use the free api), and what different between `sr` and `sr-Latn`.

 could you raise a PR for that?

**Comment by Aracki** [comment]
Before the update of `alfred-google-translate` plugin, `sr-Latn` could be set, but it doesn't work.

After the upgrade it works, but it is recognizing my Serbian Latin input as Bosnian or Croatian which is fine because it's basically the same language.

**Comment by Aracki** [comment]
Closes #2
